name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::471112565920:role/rubicon-synthetic-test-scripts
          aws-region: eu-central-1
          role-session-name: github-actions

      - name: Upload scripts to S3
        run: |
          find scripts -type f -print0 | while IFS= read -r -d $'\0' file; do
            filename=$(basename "$file")

            zip "zipped_scripts/${filename}.zip" "$file"
          done

          aws s3 sync ./zipped_scripts/ s3://rubicon-monitoring-syntethics20241106143225886000000001/scripts/ --delete
